### ISSUE TITLE
No segmentation.cfg

### ISSUE THREAD

**Issue by an-na-m** [fk128/sarcopenia-ai#1]
Hi,

I am trying to run the code on a macOS Catalina 10.15.6.

I was able to do create the docker, but when I tried to run it, I got the error message that the segmentation.cfg was not found. Where do I get it from? I don't see it in the repository.

`Successfully built 2e5e374233f9
Successfully tagged sarcopeniaai:latest
(base) User-MacBook-Air:sarcopenia-ai-master User$ docker run --rm -it -v /Users/Downloads/ -v $(pwd)/configs:/configs sarcopeniaai python -m sarcopenia_ai.apps.segmentation.trainer --config /configs/segmentation.cfg
Using TensorFlow backend.
Config file does not exists at /configs/segmentation.cfg`

**Comment by PumayHui** [comment]
I met the same problem. And I wonder if you could give configs/detection.cfg ? Thanks so much!

**Comment by fk128** [comment]
> I met the same problem. And I wonder if you could give configs/detection.cfg ? Thanks so much!

https://github.com/fk128/sarcopenia-ai/blob/master/configs/slice_detection.cfg

**Comment by fk128** [comment]
> Hi,
> 
> I am trying to run the code on a macOS Catalina 10.15.6.
> 
> I was able to do create the docker, but when I tried to run it, I got the error message that the segmentation.cfg was not found. Where do I get it from? I don't see it in the repository.
> 
> `Successfully built 2e5e374233f9 Successfully tagged sarcopeniaai:latest (base) JOSEFs-MacBook-Air:sarcopenia-ai-master josefpeter$ docker run --rm -it -v /Users/josefpeter/Downloads/ -v $(pwd)/configs:/configs sarcopeniaai python -m sarcopenia_ai.apps.segmentation.trainer --config /configs/segmentation.cfg Using TensorFlow backend. Config file does not exists at /configs/segmentation.cfg`

You'd need to get your own segmentation data to be able to train. The L3 slice detection data, however, is available for download.
