### ISSUE TITLE
Hi, great detection and segmentation tools. But I wonder if I can only use the segment model on my own test data? If yes, then what the input dataset should be for the segment model? one slice image or set of slice images? I see there are two arguments 'images_path' and 'image_list' in the tester.py, what is the meaning of these two path/folder? Could you give some samples on how to test the pre-trained model on our own dataset?

### ISSUE THREAD

**Issue by Sara666-LI** [fk128/sarcopenia-ai#13]

**Comment by fk128** [comment]
you can run it on a single slice or a batch of slices. You can have a look at the short script and see what it's doing. You can also modify that script to run on your data; once you load the model and if you have CT slice as a numpy array, then all you need to run afterwards is this part https://github.com/fk128/sarcopenia-ai/blob/master/sarcopenia_ai/apps/segmentation/tester.py#L64-L66 . I'm sorry I can't be of any further assistance.
