### ISSUE TITLE
Empty slice locations in linked data

### ISSUE THREAD

**Issue by notmatthancock** [fk128/sarcopenia-ai#4]
The README points to the data in the npz [here](https://imperialcollegelondon.app.box.com/s/mw7ysamajjcp1ot0721e6nl36xku0acv) for slice detection. But, it looks like the slice locations in this npz file are all zeros / missing:

```python
>>> data = np.load('.../path_to_imperial_college/l3_dataset_trans.npz', allow_pickle=True)
>>> print([max(v) for v in data['ydata'].item().values()])
[0, 0]
```

**Comment by fk128** [comment]
The correct link is in this section https://github.com/fk128/sarcopenia-ai#l3-annotated-dataset

The `l3_dataset_trans.npz` just contains transitional cases; you;d need `l3_dataset.npz`

https://imperialcollegelondon.box.com/s/0vt07mxy0re4zwao0sk76ywdt2s1pclm

**Comment by notmatthancock** [comment]
Thanks for the link to annotated data.

However, I'm unclear as to what you mean by "transitional cases" for the first link. The data with empty slice locations is pointed to in the README via the text,

> Download the training data from here to your data folder.

followed by a command for running training, which leads to some confusion. If the `l3_dataset.npz` data is intended to be used for training, not the data in the first link, then perhaps the README should be updated or the link to the first data be removed?

**Comment by fk128** [comment]
The transitional cases were cases that were ambiguous and were not used for training https://radiopaedia.org/articles/transitional-vertebra?lang=gb . They were later just used for testing. That's just a mistake in the README. Feel free to open a PR to correct it if you'd like.
