### ISSUE TITLE
TensorFlow version issue

### ISSUE THREAD

**Issue by alanlhutchison** [fk128/sarcopenia-ai#7]
I was attempting to install, and I encountered this problem:
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14 (from sarcopenia-ai) (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==1.14

Is there a way to easily update the tensorflow version to fix this?

**Comment by fk128** [comment]
It could be your python version. I'd recommend that you run this via docker.  I just patched the dockerfile.
